version: '3.4'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_AGENT_ENABLED=true
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebAPI/Dockerfile
    ports:
          - "8080:80"
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ConnectionStrings__DbConnection=Server=db;Database=AlicundePT;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;
    depends_on:
        - db

volumes:
  sql_data: